defaults:
  name: "Power Line 01"
  hub_no: 1
  hbridge_no: 1

fan:
  - platform: hbridge
    name: ${name}
    pin_a: hub${hub_no}_hb${hbridge_no}_i1
    pin_b: hub${hub_no}_hb${hbridge_no}_i2
    decay_mode: slow 
