# Track Switch - 1 -> 2 way
# -------------------------
# State1:    State2:
# x ==|==>   x ==|-->
#     |-->       |==>

defaults:
    name: "Track Switch 01"
    hub_no: 1
    hbridge_no: 1
    delay: 1000ms

esphome:
    on_boot:
        priority: 600
        then:
            - output.turn_off: hub${hub_no}_hb${hbridge_no}_i1
            - output.turn_off: hub${hub_no}_hb${hbridge_no}_i2
            - text_sensor.template.publish:
                id: track_switch_hub${hub_no}_hb${hbridge_no}
                state: "1"
            - button.press: track_switch_state_1_hub${hub_no}_hb${hbridge_no}

text_sensor:
  - platform: template
    name: ${name} State
    id: track_switch_hub${hub_no}_hb${hbridge_no}
    entity_category: 'DIAGNOSTIC'

button:
  - platform: template
    name: ${name} -Switcher
    id: track_switch_switcher_hub${hub_no}_hb${hbridge_no}
    icon: mdi:electric-switch
    on_press:
      then:
        if:
          condition:
            text_sensor.state:
              id: track_switch_hub${hub_no}_hb${hbridge_no}
              state: '1'
          then:
            button.press: track_switch_state_2_hub${hub_no}_hb${hbridge_no}
          else:
            button.press: track_switch_state_1_hub${hub_no}_hb${hbridge_no}
  - platform: template
    name: ${name} - State 1
    id: track_switch_state_1_hub${hub_no}_hb${hbridge_no}
    icon: mdi:electric-switch
    on_press:
      - output.turn_on:
          id: hub${hub_no}_hb${hbridge_no}_i1
      - delay: ${delay}
      - output.turn_off:
          id: hub${hub_no}_hb${hbridge_no}_i1
      - text_sensor.template.publish:
          id: track_switch_hub${hub_no}_hb${hbridge_no}
          state: "1"
  - platform: template
    name: ${name} - State 2
    id: track_switch_state_2_hub${hub_no}_hb${hbridge_no}
    icon: mdi:electric-switch
    on_press:
      - output.turn_on:
          id: hub${hub_no}_hb${hbridge_no}_i2
      - delay: ${delay}
      - output.turn_off:
          id: hub${hub_no}_hb${hbridge_no}_i2
      - text_sensor.template.publish:
          id: track_switch_hub${hub_no}_hb${hbridge_no}
          state: "2"
