# convert to packages: https://esphome.io/guides/configuration-types.html?highlight=packages#packages

substitutions:
  devicename: hrmtraincontrol01
  friendly_name: "MTrainControl01"
  node_name: htrain01
  hub_no: "1"
  voltage_multi: "0.58"

esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxx"

ota:
  password: "xxxx"

captive_portal:
  
packages:
  wifi: !include packages/wifi.yaml
  wifi_sensor: !include packages/wifi_sensor.yaml
  board1: !include
    file: packages/mtc_ha_board.yaml
    vars:
      hub_no: ${hub_no}
      board_no: 1
      i2c_address: "0x70"

  train01: !include
    file: packages/mtc_ha_power_line.yaml
    vars:
      hub_no: ${hub_no}
      board_no: "1"
      port_no: "01"
      voltage_multi: ${voltage_multi}

  yield01: !include
    file: packages/mtc_ha_yield.yaml
    vars:
      hub_no: ${hub_no}
      board_no: "1"
      port_no: "02"
      voltage_multi: ${voltage_multi}

  switch01: !include
    file: packages/mtc_ha_switch.yaml
    vars:
      hub_no: ${hub_no}
      board_no: "1"
      port_no: "03"
      voltage_multi: ${voltage_multi}

  signal01: !include
    file: packages/mtc_ha_signal.yaml
    vars:
      hub_no: ${hub_no}
      board_no: "1"
      port_no: "04"
      voltage_multi: ${voltage_multi}

  decoupler01: !include
    file: packages/mtc_ha_decoupler.yaml
    vars:
      hub_no: ${hub_no}
      board_no: "1"
      port_no: "05"
      voltage_multi: ${voltage_multi}
