# convert to packages: https://esphome.io/guides/configuration-types.html?highlight=packages#packages
# hbridge modes: power line (IN1, IN2), yield (IN1, IN2, GND), signal (IN1, GND), light (IN1, GND) or switch light (IN1, IN2, GND)

esphome:
  name: example01
  friendly_name: example01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxx"

ota:
  password: "xxxx"

captive_portal:

i2c:
  - id: i2c0
    sda: 18
    scl: 19
    scan: true

packages:
  wifi: !include packages/wifi.yaml
  pack01: !include
    file: packages/mtrain_sx1509.yaml
    vars:
      hub_no: "1"
      i2C_id: i2c0
      i2c_address: 0x3E
  power_line01: !include
    file: packages/mtrain_power_line.yaml
    vars:
      name: "Power Line 01"
      hub_no: 1
      hbridge_no: 1
  power_line02: !include
    file: packages/mtrain_power_line.yaml
    vars:
      name: "Power Line 02"
      hub_no: 1
      hbridge_no: 2
  track_switch03: !include
    file: packages/mtrain_track_switch_2way.yaml
    vars:
      name: "Track Switch 01"
      hub_no: 1
      hbridge_no: 3
      
  pack01: !include
    file: packages/mtrain_sx1509.yaml
    vars:
      hub_no: "2"
      i2C_id: i2c0
      i2c_address: 0x3F
  power_line01: !include
    file: packages/mtrain_power_line.yaml
    vars:
      name: "Power Line 01"
      hub_no: 2
      hbridge_no: 1
