name: KitBot - Last PCB check

on:
  push:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 
  pull_request:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 

jobs:
  call-workflow-passing-data:
    strategy:
      max-parallel: 1
      matrix:
        target: 
          - name: core
            panelize: 1_2
          - name: i2cmultiplexer
            panelize: 5_4
          - name: ioexpander
            panelize: 5_4
    uses: ./.github/workflows/template_kitbot_build.yaml
    with:
      pcb-dir-prefix: ${{ matrix.target.name }}
      panelize: ${{ matrix.target.panelize }}
