name: KitBot - Last PCB check

on:
  push:
    branches: 
      - main
    paths:
      - 'kibot/**.*'
      - 'pcb_*/**.*' 
  pull_request:
    branches: 
      - main
    paths:
      - 'kibot/**.*'
      - 'pcb_*/**.*' 

jobs:
  call-workflow-passing-data:
    strategy:
      max-parallel: 1
      matrix:
        target: [core]
    uses: ./.github/workflows/template_kitbot_build.yaml
    with:
      pcb-dir-prefix: ${{ matrix.target }}
      panelize: '1_2'
  call-workflow-passing-data:
    strategy:
      max-parallel: 1
      matrix:
        target: [i2cmultiplexer,ioexpander,pcb_vpdummy]
    uses: ./.github/workflows/template_kitbot_build.yaml
    with:
      pcb-dir-prefix: ${{ matrix.target }}
      panelize: '4_5'
