name: KitBot - PCB test run of production file generation

on:
  push:
    branches: 
      - main
    paths:
      - 'kibot/**.*'
      - 'pcb_*/**.*' 
  pull_request:
    branches: 
      - main
    paths:
      - 'kibot/**.*'
      - 'pcb_*/**.*' 

jobs:
  Fabrication-Core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate fabrication - Core
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/base.kibot.yaml
          dir: pcb_core/Fabrication
          schema: 'pcb_core/project.kicad_sch'
          board: 'pcb_core/project.kicad_pcb'
          verbose: 0
      - name: Generate fabrication - Production
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/production.kibot.yaml
          dir: pcb_core/Fabrication/production
          schema: 'pcb_core/project.kicad_sch'
          board: 'pcb_core/project.kicad_pcb'
          verbose: 0
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Fabrication_Core
          path: |
            pcb_core/Fabrication/
          if-no-files-found: warn
          retention-days: 1
