name: KitBot - Last PCB check

on:
  push:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 
  pull_request:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 

jobs:
  ERC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        schema: 'pcb_core/project.kicad_sch'
        board: 'pcb_core/project.kicad_pcb'
        verbose: 0
        dir: Generated
        skip: drc
        targets: __NONE__
    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_Output
        path: Generated
        retention-days: 1

  DRC:
    runs-on: ubuntu-latest
    needs: ERC
    steps:
    - uses: actions/checkout@v4
    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        schema: 'pcb_core/project.kicad_sch'
        board: 'pcb_core/project.kicad_pcb'
        verbose: 0
        dir: Generated
        skip: erc
        targets: __NONE__
    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_Output
        path: Generated
        retention-days: 1

  MasterESP32S3:
    name: "Primary node variant with ESP32-S3"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        dir: pcb_core/primarynodeesp32s3
        schema: 'pcb_core/project.kicad_sch'
        board: 'pcb_core/project.kicad_pcb'
        verbose: 0
        variant: PrimaryNodeESP32S3
        skip: erc,drc
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/production.kibot.yaml
        dir: pcb_core/primarynodeesp32s3/production
        schema: 'pcb_core/project.kicad_sch'
        board: 'pcb_core/project.kicad_pcb'
        verbose: 0
        variant: PrimaryNodeESP32S3
        skip: erc,drc
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: variant_primarynodeesp32s3
        path: pcb_core/primarynodeesp32s3
        retention-days: 1
  
  MasterESP32Devkit:
    name: "Primary node variant with ESP32-Devkit"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        dir: pcb_core/primarynodeesp32devkit
        schema: 'pcb_core/project.kicad_sch'
        board: 'pcb_core/project.kicad_pcb'
        verbose: 0
        variant: PrimaryNodeESP32Devkit
        skip: erc,drc
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/production.kibot.yaml
        dir: pcb_core/primarynodeesp32devkit/production
        schema: 'pcb_core/project.kicad_sch'
        board: 'pcb_core/project.kicad_pcb'
        verbose: 0
        variant: PrimaryNodeESP32Devkit
        skip: erc,drc
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: variant_primarynodeesp32devkit
        path: pcb_core/primarynodeesp32devkit
        retention-days: 1
        
  Slave:
    name: "Sub node variant"
    runs-on: ubuntu-latest
    needs: [ERC, DRC]
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        dir: pcb_core/subnode
        schema: 'pcb_core/project.kicad_sch'
        board: 'pcb_core/project.kicad_pcb'
        verbose: 0
        variant: SubNode
        skip: erc,drc
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/production.kibot.yaml
        dir: pcb_core/subnode/production
        schema: 'pcb_core/project.kicad_sch'
        board: 'pcb_core/project.kicad_pcb'
        verbose: 0
        variant: SubNode
        skip: erc,drc
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: variant_subnode
        path: pcb_core/subnode
        retention-days: 1

