name: KitBot - Last PCB check

on:
  push:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 
  pull_request:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 

jobs:
  call-workflow-passing-data:
    strategy:
      max-parallel: 1
      matrix:
        target: [core,i2cmultiplexer,ioexpander]
        panelize: [5_4]
        include:
          - target: core
            panelize: 1_2
        exclude:
          - target: core
            panelize: 5_4
    uses: ./.github/workflows/template_kitbot_build.yaml
    with:
      pcb-dir-prefix: ${{ matrix.target }}
      panelize: ${{ matrix.panelize }}
