name: KitBot - PCB production file generation

on:
  push:
    tags:
      - '*'

jobs:
  Fabrication-Controller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate fabrication - Base
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/base.kibot.yaml
          dir: pcb_controller/Fabrication
          schema: 'pcb_controller/project.kicad_sch'
          board: 'pcb_controller/project.kicad_pcb'
          verbose: 0
      - name: Generate fabrication - Production
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/production.kibot.yaml
          dir: pcb_controller/Fabrication/production
          schema: 'pcb_controller/project.kicad_sch'
          board: 'pcb_controller/project.kicad_pcb'
          verbose: 0
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Fabrication_Controller
          path: |
            pcb_controller/Fabrication/fabrication_controller.zip
          if-no-files-found: warn
          retention-days: 1
  Fabrication-HBridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate fabrication - Base
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/base.kibot.yaml
          dir: pcb_hbridge/Fabrication
          schema: 'pcb_hbridge/project.kicad_sch'
          board: 'pcb_hbridge/project.kicad_pcb'
          verbose: 0
      - name: Generate fabrication - Production
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/production.kibot.yaml
          dir: pcb_hbridge/Fabrication/production
          schema: 'pcb_hbridge/project.kicad_sch'
          board: 'pcb_hbridge/project.kicad_pcb'
          verbose: 0
      - name: Generate fabrication - Panel
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: pcb_hbridge/panel.kibot.yaml
          dir: pcb_hbridge/Fabrication/production_panel
          schema: 'pcb_hbridge/project.kicad_sch'
          board: 'pcb_hbridge/project.kicad_pcb'
          verbose: 0
      - name: Generate fabrication - Panel Production
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/production.kibot.yaml
          dir: pcb_hbridge/Fabrication/production_panel
          schema: 'pcb_hbridge/project.kicad_sch'
          board: 'pcb_hbridge/Fabrication/production_panel/project-panel.kicad_pcb'
          verbose: 0
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Fabrication_HBridge
          path: |
            pcb_hbridge/Fabrication/fabrication_hbridge.zip
          if-no-files-found: warn
          retention-days: 1
  Fabrication-Main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate fabrication - Base
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/base.kibot.yaml
          dir: pcb_main/Fabrication
          schema: 'pcb_main/project.kicad_sch'
          board: 'pcb_main/project.kicad_pcb'
          verbose: 0
      - name: Generate fabrication - Production
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/production.kibot.yaml
          dir: pcb_main/Fabrication/production
          schema: 'pcb_main/project.kicad_sch'
          board: 'pcb_main/project.kicad_pcb'
          verbose: 0
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Fabrication_Main
          path: |
            pcb_main/Fabrication/fabrication_main.zip
          if-no-files-found: warn
          retention-days: 1
  Fabrication-Power:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate fabrication - Base
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/base.kibot.yaml
          dir: pcb_power/Fabrication
          schema: 'pcb_power/project.kicad_sch'
          board: 'pcb_power/project.kicad_pcb'
          verbose: 0
      - name: Generate fabrication - Production
        uses: INTI-CMNB/KiBot@v2_k8
        with:
          config: kibot/production.kibot.yaml
          dir: pcb_power/Fabrication/production
          schema: 'pcb_power/project.kicad_sch'
          board: 'pcb_power/project.kicad_pcb'
          verbose: 0
      - name: Retrieve results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Fabrication_Power
          path: |
            pcb_power/Fabrication/fabrication_power.zip
          if-no-files-found: warn
          retention-days: 1
  Create-Release:
    runs-on: ubuntu-latest
    needs: [Fabrication-Controller,Fabrication-HBridge,Fabrication-Main,Fabrication-Power]
    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          path: fabrication
          pattern: Fabrication_*
      - name: release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Release Asset - Controller
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fabrication/fabrication_controller.zip
          asset_name: Fabrication Controller
          asset_content_type: application/zip
      - name: Upload Release Asset - HBridge
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fabrication/fabrication_hbridge.zip
          asset_name: Fabrication HBridge
          asset_content_type: application/zip
      - name: Upload Release Asset - Main
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fabrication/fabrication_main.zip
          asset_name: Fabrication Main
          asset_content_type: application/zip
      - name: Upload Release Asset - Power
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./fabrication/fabrication_power.zip
          asset_name: Fabrication Power
          asset_content_type: application/zip
